### ISSUE TITLE
HeartBeat thread stays alive and pings even if SwapBot thread has died

### ISSUE THREAD

**Issue by dlabrie** [itslupus/burntbot#2]
There's been reports of bots showing as online but the bot didn't return.

Suggestion would be a global variable that the swap bot updates and the heart beat thread checks before pinging the api.

**Comment by lucashuy** [comment]
Yeah I first designed it that way since the bot thread would auto restart in the case of a crash, so the heart beat thread would still technically be correct that the bot is alive.

However, I do see a case where the bot will crash, but auto restart the five times without success and finally stop the program all while the heart beat is up.

I'll likely do as suggested and create some sort of state the bot can update so that the heart beat can check it. This state might also be useful in the web UI.
